export const mockVisitors = [
  {
    id: '1',
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@company.com",
    company: "TechCorp India",
    jobTitle: "Senior Software Engineer",
    phone: "+91 98765 43210",
    country: "India",
    interests: ["AI/ML", "Web Development", "Cloud Computing"],
    customData: {
      location: "Mumbai, Maharashtra",
      avatar: "RS",
      matchScore: 95,
      industry: "Technology",
      experience: "5+ years",
      lookingFor: ["Partnerships", "New Technologies", "Networking"]
    },
    status: 'registered' as const,
    type: 'visitor' as const,
    eventId: 'EVT-001',
    registrationDate: new Date('2024-01-15'),
    invitationSent: true,
    invitationDate: new Date('2024-01-10'),
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    firstName: "Priya",
    lastName: "Patel",
    email: "priya@startup.com",
    company: "StartupXYZ",
    jobTitle: "Product Manager",
    phone: "+91 98765 43211",
    country: "India",
    interests: ["Product Strategy", "UX Design", "Analytics"],
    customData: {
      location: "Pune, Maharashtra",
      avatar: "PP",
      matchScore: 87,
      industry: "Fintech",
      experience: "3+ years",
      lookingFor: ["Investment", "Mentorship", "Partnerships"]
    },
    status: 'checked-in' as const,
    type: 'visitor' as const,
    eventId: 'EVT-001',
    registrationDate: new Date('2024-01-12'),
    invitationSent: true,
    invitationDate: new Date('2024-01-08'),
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: '3',
    firstName: "Amit",
    lastName: "Kumar",
    email: "amit@enterprise.com",
    company: "Enterprise Solutions Ltd",
    jobTitle: "Chief Technology Officer",
    phone: "+91 98765 43212",
    country: "India",
    interests: ["Cloud Computing", "DevOps", "Cybersecurity"],
    customData: {
      location: "Delhi, NCR",
      avatar: "AK",
      matchScore: 92,
      industry: "Enterprise Software",
      experience: "10+ years",
      lookingFor: ["Strategic Partnerships", "Technology Solutions"]
    },
    status: 'registered' as const,
    type: 'visitor' as const,
    eventId: 'EVT-001',
    registrationDate: new Date('2024-01-14'),
    invitationSent: true,
    invitationDate: new Date('2024-01-09'),
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: '4',
    firstName: "Sneha",
    lastName: "Reddy",
    email: "sneha@healthtech.com",
    company: "HealthTech Innovations",
    jobTitle: "Founder & CEO",
    phone: "+91 98765 43213",
    country: "India",
    interests: ["Healthcare Technology", "AI in Medicine", "Digital Health"],
    customData: {
      location: "Hyderabad, Telangana",
      avatar: "SR",
      matchScore: 89,
      industry: "Healthcare",
      experience: "7+ years",
      lookingFor: ["Funding", "Healthcare Partnerships", "Regulatory Guidance"]
    },
    status: 'registered' as const,
    type: 'visitor' as const,
    eventId: 'EVT-001',
    registrationDate: new Date('2024-01-13'),
    invitationSent: true,
    invitationDate: new Date('2024-01-07'),
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-13'),
  },
  {
    id: '5',
    firstName: "Vikram",
    lastName: "Singh",
    email: "vikram@edtech.com",
    company: "EduFuture Platform",
    jobTitle: "VP of Engineering",
    phone: "+91 98765 43214",
    country: "India",
    interests: ["Educational Technology", "Mobile Development", "AR/VR"],
    customData: {
      location: "Bangalore, Karnataka",
      avatar: "VS",
      matchScore: 84,
      industry: "Education Technology",
      experience: "8+ years",
      lookingFor: ["Technical Partnerships", "Innovation", "Talent Acquisition"]
    },
    status: 'invited' as const,
    type: 'visitor' as const,
    eventId: 'EVT-001',
    invitationSent: true,
    invitationDate: new Date('2024-01-11'),
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
  },
  {
    id: '6',
    firstName: "Ananya",
    lastName: "Krishnan",
    email: "ananya@greentech.com",
    company: "GreenTech Solutions",
    jobTitle: "Sustainability Director",
    phone: "+91 98765 43215",
    country: "India",
    interests: ["Clean Energy", "Environmental Tech", "Sustainability"],
    customData: {
      location: "Chennai, Tamil Nadu",
      avatar: "AK",
      matchScore: 91,
      industry: "Clean Technology",
      experience: "6+ years",
      lookingFor: ["Green Partnerships", "Environmental Solutions", "Policy Advocacy"]
    },
    status: 'checked-in' as const,
    type: 'visitor' as const,
    eventId: 'EVT-001',
    registrationDate: new Date('2024-01-16'),
    invitationSent: true,
    invitationDate: new Date('2024-01-06'),
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-16'),
  }
];

export const mockExhibitors = [
  {
    id: '7',
    firstName: "Rajesh",
    lastName: "Gupta",
    email: "rajesh@aitech.com",
    company: "AI Technologies Inc",
    jobTitle: "Chief Executive Officer",
    phone: "+91 98765 43216",
    country: "India",
    interests: ["Artificial Intelligence", "Machine Learning", "Enterprise AI"],
    customData: {
      location: "Gurgaon, Haryana",
      avatar: "RG",
      matchScore: 96,
      industry: "AI/ML Solutions",
      experience: "12+ years",
      lookingFor: ["Enterprise Clients", "AI Implementation", "Strategic Alliances"],
      boothNumber: "A-101",
      boothSize: "Large",
      products: ["AI Chatbots", "ML Analytics", "Computer Vision"],
      website: "https://aitech.com"
    },
    status: 'registered' as const,
    type: 'exhibitor' as const,
    eventId: 'EVT-001',
    registrationDate: new Date('2024-01-10'),
    invitationSent: true,
    invitationDate: new Date('2024-01-05'),
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: '8',
    firstName: "Kavya",
    lastName: "Nair",
    email: "kavya@cloudworks.com",
    company: "CloudWorks Solutions",
    jobTitle: "Sales Director",
    phone: "+91 98765 43217",
    country: "India",
    interests: ["Cloud Infrastructure", "DevOps", "SaaS Solutions"],
    customData: {
      location: "Kochi, Kerala",
      avatar: "KN",
      matchScore: 88,
      industry: "Cloud Computing",
      experience: "6+ years",
      lookingFor: ["Cloud Adoption", "Enterprise Clients", "Partnership"],
      boothNumber: "B-205",
      boothSize: "Medium",
      products: ["Cloud Migration", "DevOps Tools", "Infrastructure Management"],
      website: "https://cloudworks.com"
    },
    status: 'checked-in' as const,
    type: 'exhibitor' as const,
    eventId: 'EVT-001',
    registrationDate: new Date('2024-01-11'),
    invitationSent: true,
    invitationDate: new Date('2024-01-04'),
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-11'),
  },
  {
    id: '9',
    firstName: "Arjun",
    lastName: "Mehta",
    email: "arjun@cybersec.com",
    company: "CyberSecure Pro",
    jobTitle: "Security Consultant",
    phone: "+91 98765 43218",
    country: "India",
    interests: ["Cybersecurity", "Network Security", "Ethical Hacking"],
    customData: {
      location: "Ahmedabad, Gujarat",
      avatar: "AM",
      matchScore: 90,
      industry: "Cybersecurity",
      experience: "8+ years",
      lookingFor: ["Security Audits", "Compliance Solutions", "Training"],
      boothNumber: "C-310",
      boothSize: "Small",
      products: ["Security Audits", "Penetration Testing", "Security Training"],
      website: "https://cybersecure.com"
    },
    status: 'registered' as const,
    type: 'exhibitor' as const,
    eventId: 'EVT-001',
    registrationDate: new Date('2024-01-12'),
    invitationSent: true,
    invitationDate: new Date('2024-01-03'),
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: '10',
    firstName: "Deepika",
    lastName: "Joshi",
    email: "deepika@fintech.com",
    company: "FinTech Innovations",
    jobTitle: "Head of Business Development",
    phone: "+91 98765 43219",
    country: "India",
    interests: ["Financial Technology", "Digital Payments", "Blockchain"],
    customData: {
      location: "Mumbai, Maharashtra",
      avatar: "DJ",
      matchScore: 85,
      industry: "Financial Services",
      experience: "5+ years",
      lookingFor: ["Financial Partnerships", "Payment Solutions", "RegTech"],
      boothNumber: "D-415",
      boothSize: "Large",
      products: ["Digital Wallets", "Payment Gateway", "KYC Solutions"],
      website: "https://fintech-innovations.com"
    },
    status: 'registered' as const,
    type: 'exhibitor' as const,
    eventId: 'EVT-001',
    registrationDate: new Date('2024-01-13'),
    invitationSent: true,
    invitationDate: new Date('2024-01-02'),
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-13'),
  }
];

export const mockEvent = {
  id: 'evt-001',
  eventId: 'EVT-2024-TECH-001',
  name: 'AI & Technology Summit 2024',
  description: 'The premier technology conference showcasing the latest in AI, machine learning, and emerging technologies.',
  startDate: new Date('2024-03-15T09:00:00'),
  endDate: new Date('2024-03-17T18:00:00'),
  location: 'India Expo Centre, Greater Noida',
  maxVisitors: 500,
  maxExhibitors: 100,
  status: 'active' as const,
  createdBy: 'it-admin-001',
  eventAdminId: 'event-admin-001',
  customAttributes: [],
  marketingAbbreviation: 'TECH2024',
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-15'),
};

export const mockStats = {
  totalEvents: 1,
  activeEvents: 1,
  totalParticipants: 10,
  registeredVisitors: 6,
  registeredExhibitors: 4,
  pendingInvitations: 1,
  matchmakingScore: 89,
}; 